[package]
name = "esh-providers-k8s"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Kubernetes secrets provider for Env-Secret-Hydrator"

[dependencies]
esh-core = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
esh-test-support = { workspace = true }

[lints]
workspace = true
