[package]
name = "esh-providers-k8s"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "Kubernetes secrets provider for Env-Secret-Hydrator"
documentation = "https://docs.rs/esh-providers-k8s"
readme = "README.md"
keywords.workspace = true
categories.workspace = true
include = [
    "src/**/*",
    "Cargo.toml",
    "README.md",
    "LICENSE-MIT",
    "LICENSE-APACHE",
]

[dependencies]
esh-core = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
esh-test-support = { workspace = true }

[lints]
workspace = true
